version: "3.8"

services:
  postgres:
    image: postgres:13.2
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"
    command: /bin/bash -c "alembic upgrade head && python main.py"
    depends_on:
      - postgres
    env_file:
      - .env
