"""added value field into Like model

Revision ID: 357583c7cf03
Revises: 9968ebccff77
Create Date: 2023-07-06 09:40:59.657645

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '357583c7cf03'
down_revision = '9968ebccff77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('value', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('like', 'value')
    # ### end Alembic commands ###
